package br.tulli.jm.view;

public class LoginWindow extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;

	public LoginWindow() {
        initComponents();
        configureComponents();

        //autologin
        jBtnLoginOk.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnLoginOk = new javax.swing.JButton();
        jBtnLoginCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmLogin"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jBtnLoginOk.setText("Ok");
        jBtnLoginOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginOkActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnLoginOk);
        jBtnLoginOk.setBounds(40, 220, 45, 23);

        jBtnLoginCancel.setText("Cancel");
        jBtnLoginCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnLoginCancel);
        jBtnLoginCancel.setBounds(330, 220, 65, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoginOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginOkActionPerformed
        new MainWindow();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnLoginOkActionPerformed

    private void jBtnLoginCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnLoginCancelActionPerformed

    public static void main(String[] args) {
        new LoginWindow();
    }

    private void configureComponents() {
        this.setResizable(false);
        this.setBounds(150, 100, 450, 300);
        this.setLocationRelativeTo(null);
        jBtnLoginOk.setBounds(125, 220, 90, 30);
        jBtnLoginCancel.setBounds(235, 220, 90, 30);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoginCancel;
    private javax.swing.JButton jBtnLoginOk;
    // End of variables declaration//GEN-END:variables
}
