package br.tulli.jm.view;

import java.awt.Dimension;
import java.awt.Toolkit;

public class MainWindow extends javax.swing.JFrame {

    public MainWindow() {
        initComponents();
        configureComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelButton = new javax.swing.JPanel();
        jBtnExit = new javax.swing.JButton();
        jPanelWindow = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuRegister = new javax.swing.JMenu();
        jMnItmDepartment = new javax.swing.JMenuItem();
        jMnItmTeacher = new javax.swing.JMenuItem();
        jMnItmDiscipline = new javax.swing.JMenuItem();
        jMnItmCourse = new javax.swing.JMenuItem();
        jMnItmStudent = new javax.swing.JMenuItem();
        jMenuSystem = new javax.swing.JMenu();
        jMnItmUsers = new javax.swing.JMenuItem();
        jMnItmParameters = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();
        jMnItmExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Management System");
        setName("frmMainWindow"); // NOI18N
        setResizable(false);

        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanelButton.add(jBtnExit);

        getContentPane().add(jPanelButton, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanelWindowLayout = new javax.swing.GroupLayout(jPanelWindow);
        jPanelWindow.setLayout(jPanelWindowLayout);
        jPanelWindowLayout.setHorizontalGroup(
            jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanelWindowLayout.setVerticalGroup(
            jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelWindow, java.awt.BorderLayout.CENTER);

        jMenuRegister.setText("Register");

        jMnItmDepartment.setText("1 - Department");
        jMnItmDepartment.setEnabled(false);
        jMenuRegister.add(jMnItmDepartment);

        jMnItmTeacher.setText("2 - Teacher");
        jMnItmTeacher.setEnabled(false);
        jMenuRegister.add(jMnItmTeacher);

        jMnItmDiscipline.setText("3 - Discipline");
        jMnItmDiscipline.setEnabled(false);
        jMenuRegister.add(jMnItmDiscipline);

        jMnItmCourse.setText("4 - Course");
        jMnItmCourse.setEnabled(false);
        jMenuRegister.add(jMnItmCourse);

        jMnItmStudent.setText("5 - Student");
        jMnItmStudent.setEnabled(false);
        jMenuRegister.add(jMnItmStudent);

        jMenuBar.add(jMenuRegister);

        jMenuSystem.setText("System");

        jMnItmUsers.setText("Users");
        jMnItmUsers.setEnabled(false);
        jMenuSystem.add(jMnItmUsers);

        jMnItmParameters.setText("Parameters");
        jMnItmParameters.setEnabled(false);
        jMenuSystem.add(jMnItmParameters);

        jMenuBar.add(jMenuSystem);

        jMenuExit.setText("Exit");

        jMnItmExit.setText("Exit System");
        jMnItmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnItmExitActionPerformed(evt);
            }
        });
        jMenuExit.add(jMnItmExit);

        jMenuBar.add(jMenuExit);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jMnItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnItmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnItmExitActionPerformed

    private void configureComponents() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(100, 100, Math.round(screenSize.width * 0.8F) , Math.round(screenSize.height * 0.8F));
        this.setLocationRelativeTo(null);
        jPanelWindow.setBounds(this.getBounds());
        jMnItmDepartment.setEnabled(true);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenu jMenuRegister;
    private javax.swing.JMenu jMenuSystem;
    private javax.swing.JMenuItem jMnItmCourse;
    private javax.swing.JMenuItem jMnItmDepartment;
    private javax.swing.JMenuItem jMnItmDiscipline;
    private javax.swing.JMenuItem jMnItmExit;
    private javax.swing.JMenuItem jMnItmParameters;
    private javax.swing.JMenuItem jMnItmStudent;
    private javax.swing.JMenuItem jMnItmTeacher;
    private javax.swing.JMenuItem jMnItmUsers;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelWindow;
    // End of variables declaration//GEN-END:variables
}
